export {
  buildDivinationContext,
  performTimeBasedDivination,
  performNumberBasedDivination,
  buildTimeBasedInput,
  adjustDateForTyBoundary,
  getHourChiIndex,
  getYearChiIndex,
  getTrigramById,
  findHexagram,
  calculateUpperTrigramFromTime,
  calculateLowerTrigramFromTime,
  calculateUpperTrigramFromNumbers,
  calculateLowerTrigramFromNumbers,
  calculateMovingLineFromTime,
  calculateMovingLineFromNumbers,
  getMainHexagram,
  getMutualHexagram,
  getChangedHexagram,
  determineTheDung,
  resolveCungAndThe,
  deriveLucThan,
  resolveHaoDetails,
  assertMaiHoaChiIndex,
  ensureHexagramsLoaded,
  calculateSeasonalStrength,
} from '@/utils/maiHoaEngine';
export {
  interpretDivination,
  getElementInteraction,
  assessTheDung,
  getSeasonFromLunarMonth,
  getElementStrength,
  describeTemporalInfluence,
  getHexagramMeaning,
  getMovingLineText,
  getMovingLinePrediction,
  getCategoryPredictions,
  analyzeDungThan,
  analyzeSecondaryHexagram,
} from '@/utils/maiHoaInterpreter';
export type {
  Trigram,
  Hexagram,
  TimeBasedInput,
  NumberBasedInput,
  DivinationResult,
  DivinationContext,
  DivineReadingSummary,
  NguHanhRelation,
  ElementStrength,
  TheDungAssessment,
  HaoText,
  HexagramCategoryPredictions,
  MovingLinePrediction,
  CalendarMode,
} from '@/types/maiHoa';
