/**
 * Tử Vi Canonical Star-to-Star & Positional Interaction Rules Engine
 *
 * Classical references:
 * - Tử Vi Đẩu Số Toàn Thư (Trần Đoàn / La Hồng Tiên) — Thái Vi Phú & Cốt Tủy Phú
 * - Tử Vi Đẩu Số Tân Biên (Vân Đằng Thái Thứ Lang)
 * - Trung Châu Tam Hợp Phái (Vương Đình Chi — Tử Vi Đẩu Số Giảng Nghĩa)
 * - Tử Vi Đẩu Số Phú Giải (Nguyễn Phát Lộc, Phan Tử Ngư)
 */

import type { TuViPalace, PositionalSemantic, PositionalSemanticType } from '../../types/tuvi';
import { detectDoiCung, detectTamHopPalaces, detectNhiHopPalace } from './palaceGeometry';

// ── Elemental Branches mapping for Nhị Hợp ───────────────────
export const BRANCH_ELEMENT: Record<string, 'Thủy' | 'Hỏa' | 'Mộc' | 'Kim' | 'Thổ'> = {
  Tý: 'Thủy',
  Sửu: 'Thổ',
  Dần: 'Mộc',
  Mão: 'Mộc',
  Thìn: 'Thổ',
  Tỵ: 'Hỏa',
  Ngọ: 'Hỏa',
  Mùi: 'Thổ',
  Thân: 'Kim',
  Dậu: 'Kim',
  Tuất: 'Thổ',
  Hợi: 'Thủy',
};

// ── Five Element Relations ────────────────────────────────────
export function getElementRelation(
  sourceElem: string,
  targetElem: string,
): 'sinh_nhap' | 'sinh_xuat' | 'khac_nhap' | 'khac_xuat' | 'ty_hoa' {
  if (sourceElem === targetElem) return 'ty_hoa';
  const sinhMap: Record<string, string> = {
    Mộc: 'Hỏa',
    Hỏa: 'Thổ',
    Thổ: 'Kim',
    Kim: 'Thủy',
    Thủy: 'Mộc',
  };
  const khacMap: Record<string, string> = {
    Mộc: 'Thổ',
    Thổ: 'Thủy',
    Thủy: 'Hỏa',
    Hỏa: 'Kim',
    Kim: 'Mộc',
  };

  if (sinhMap[sourceElem] === targetElem) return 'sinh_xuat'; // Target is generated by Source
  if (sinhMap[targetElem] === sourceElem) return 'sinh_nhap'; // Source is generated by Target (Target supports Source)
  if (khacMap[sourceElem] === targetElem) return 'khac_xuat'; // Source controls Target
  if (khacMap[targetElem] === sourceElem) return 'khac_nhap'; // Target controls Source
  return 'ty_hoa';
}

export interface EvaluatedStarInteraction {
  type: PositionalSemanticType;
  label: string;
  stars: string[];
  sourcePalaces: string[];
  hostStars: string[];
  classicalPattern?: string;
  nature: 'cat' | 'hung' | 'trung-hoa' | 'kich-phat';
  description: string;
  actionableHint?: string;
}

/**
 * Evaluates detailed Giáp Cung (Brackets: Hiệp / Hiếp) interactions
 */
export function evaluateBracketInteractions(palace: TuViPalace, allPalaces: TuViPalace[]): PositionalSemantic[] {
  const results: PositionalSemantic[] = [];
  const leftIdx = (palace.id - 1 + 12) % 12;
  const rightIdx = (palace.id + 1) % 12;
  const leftPalace = allPalaces[leftIdx];
  const rightPalace = allPalaces[rightIdx];
  if (!leftPalace || !rightPalace) return results;

  const hostChinhTinh = palace.chinhTinh.map((s) => s.name);
  const leftStars = [...leftPalace.chinhTinh, ...leftPalace.phuTinh, ...leftPalace.satTinh].map((s) => s.name);
  const rightStars = [...rightPalace.chinhTinh, ...rightPalace.phuTinh, ...rightPalace.satTinh].map((s) => s.name);
  const leftTuHoa = leftPalace.tuHoa.map((th) => `Hóa ${th.type} (${th.starName})`);
  const rightTuHoa = rightPalace.tuHoa.map((th) => `Hóa ${th.type} (${th.starName})`);

  const hasLeft = (star: string) => leftStars.includes(star) || leftTuHoa.some((t) => t.includes(star));
  const hasRight = (star: string) => rightStars.includes(star) || rightTuHoa.some((t) => t.includes(star));

  // 1. Tài Ấm Giáp Ấn (財蔭夾印)
  const isThienTuongHost = hostChinhTinh.includes('Thiên Tướng');
  const hasLocLeft = hasLeft('Hóa Lộc') || hasLeft('Lộc Tồn');
  const hasLocRight = hasRight('Hóa Lộc') || hasRight('Lộc Tồn');
  const hasLuongLeft = hasLeft('Thiên Lương');
  const hasLuongRight = hasRight('Thiên Lương');
  if (isThienTuongHost && ((hasLocLeft && hasLuongRight) || (hasLocRight && hasLuongLeft))) {
    const locPalace = hasLocLeft ? leftPalace.name : rightPalace.name;
    const luongPalace = hasLuongLeft ? leftPalace.name : rightPalace.name;
    results.push({
      type: 'hiep',
      label: 'Hiệp (Giáp Cung Đặc Cách)',
      stars: ['Thiên Lương', 'Hóa Lộc / Lộc Tồn'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: ['Thiên Tướng'],
      classicalPattern: 'Tài Ấm Giáp Ấn (財蔭夾印)',
      nature: 'cat',
      description: `Thiên Tướng tại bản cung đắc thế đại quý "Tài Ấm Giáp Ấn" nhờ Lộc tinh tại ${locPalace} và Ấm tinh Thiên Lương tại ${luongPalace} kèm hai bên sườn. Tinh thần trượng nghĩa, có uy tín quản lý, được hưởng phước ấm tài chính từ gia đình hoặc bề trên nâng đỡ vững chắc.`,
      actionableHint:
        'Chủ động nắm bắt cơ hội quản lý tài chính, mở rộng dự án và giữ vững uy tín trung thực để thành tựu ngày càng hiển hách.',
    });
  }

  // 2. Hình Kỵ Giáp Ấn (刑忌夾印)
  const hasKyLeft = hasLeft('Hóa Kỵ');
  const hasKyRight = hasRight('Hóa Kỵ');
  const hasHinhLeft = hasLeft('Kình Dương') || hasLeft('Thiên Hình');
  const hasHinhRight = hasRight('Kình Dương') || hasRight('Thiên Hình');
  if (isThienTuongHost && ((hasKyLeft && hasHinhRight) || (hasKyRight && hasHinhLeft))) {
    const kyPalace = hasKyLeft ? leftPalace.name : rightPalace.name;
    const hinhPalace = hasHinhLeft ? leftPalace.name : rightPalace.name;
    results.push({
      type: 'hiepHung',
      label: 'Hiếp (Giáp Sát Bất Lợi)',
      stars: ['Hóa Kỵ', 'Kình Dương / Thiên Hình'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: ['Thiên Tướng'],
      classicalPattern: 'Hình Kỵ Giáp Ấn (刑忌夾印)',
      nature: 'hung',
      description: `Thiên Tướng tại bản cung bị thế hiểm "Hình Kỵ Giáp Ấn" kẹp chặt bởi Hóa Kỵ tại ${kyPalace} và Sát tinh/Hình tại ${hinhPalace}. Dễ gặp áp lực pháp lý, tranh chấp hợp đồng, bị đối tác bội tín hoặc chịu ơn hóa oán.`,
      actionableHint:
        'Tuyệt đối cẩn trọng khi đứng tên bảo lãnh, ký kết hợp đồng; dĩ hòa vi quý, tránh can thiệp sâu vào chuyện thị phi của người khác.',
    });
  }

  // 3. Giáp Tả Hữu (Quân thần giáp mệnh/cung)
  if ((hasLeft('Tả Phụ') && hasRight('Hữu Bật')) || (hasLeft('Hữu Bật') && hasRight('Tả Phụ'))) {
    const hostDesc = hostChinhTinh.length > 0 ? `tinh hệ ${hostChinhTinh.join(' - ')}` : 'cung vị';
    results.push({
      type: 'hiep',
      label: 'Hiệp (Giáp Tả Hữu)',
      stars: ['Tả Phụ', 'Hữu Bật'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Tả Hữu Giáp Cung (左右夾命/宮)',
      nature: 'cat',
      description: `Hai bên giáp cung (${leftPalace.name} & ${rightPalace.name}) có cặp phụ tinh Tả Phụ - Hữu Bật phò tá kẹp hai bên. Giúp ${hostDesc} được trợ lực đa phương, trong mọi bước đi đều có cộng sự, bạn bè đắc lực kề vai sát cánh.`,
      actionableHint:
        'Xây dựng tinh thần làm việc nhóm, chia sẻ quyền lợi công bằng với cộng sự để phát huy tối đa sức mạnh tập thể.',
    });
  }

  // 4. Giáp Khôi Việt (Giáp Quý Nhân)
  if ((hasLeft('Thiên Khôi') && hasRight('Thiên Việt')) || (hasLeft('Thiên Việt') && hasRight('Thiên Khôi'))) {
    results.push({
      type: 'hiep',
      label: 'Hiệp (Giáp Khôi Việt)',
      stars: ['Thiên Khôi', 'Thiên Việt'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Khôi Việt Giáp Cung (魁鉞夾命/宮)',
      nature: 'cat',
      description: `Cung vị được cặp quý tinh Thiên Khôi - Thiên Việt kẹp hai bên sườn (${leftPalace.name} & ${rightPalace.name}). Luôn có cơ hội gặp quý nhân dẫn lối, được người có tầm ảnh hưởng cất nhắc và che chở lúc hoạn nạn.`,
      actionableHint:
        'Chủ động học hỏi từ tiền bối, tôn trọng người đi trước để đón nhận trọn vẹn duyên lành tương trợ.',
    });
  }

  // 5. Giáp Xương Khúc (Giáp Văn Tinh)
  if ((hasLeft('Văn Xương') && hasRight('Văn Khúc')) || (hasLeft('Văn Khúc') && hasRight('Văn Xương'))) {
    results.push({
      type: 'hiep',
      label: 'Hiệp (Giáp Xương Khúc)',
      stars: ['Văn Xương', 'Văn Khúc'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Xương Khúc Giáp Cung (昌曲夾命/宮)',
      nature: 'cat',
      description: `Được cặp Văn Tinh Văn Xương - Văn Khúc kẹp hai bên (${leftPalace.name} & ${rightPalace.name}), tăng cường trí tuệ thông tuệ, phong thái thanh nhã, tư duy mạch lạc và khiếu thẩm mỹ nghệ thuật.`,
      actionableHint:
        'Phát huy năng lực ngôn ngữ, văn thư, học thuật hoặc nghệ thuật để tạo dựng thương hiệu cá nhân thanh nhã.',
    });
  }

  // 6. Giáp Nhật Nguyệt (Nhật Nguyệt Giáp Cung)
  if ((hasLeft('Thái Dương') && hasRight('Thái Âm')) || (hasLeft('Thái Âm') && hasRight('Thái Dương'))) {
    results.push({
      type: 'hiep',
      label: 'Hiệp (Giáp Nhật Nguyệt)',
      stars: ['Thái Dương', 'Thái Âm'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Nhật Nguyệt Giáp Mệnh/Cung (日月夾命)',
      nature: 'cat',
      description: `Thế Nhật Nguyệt kẹp hai bên sườn (${leftPalace.name} & ${rightPalace.name}) tựa như vầng nhật nguyệt cùng soi chiếu. Mang lại tầm nhìn sáng suốt, tâm hồn ấm áp, vừa có chí khí hào sảng vừa có chiều sâu tích lũy.`,
      actionableHint:
        'Kết hợp hài hòa giữa mở rộng đối ngoại (Dương) và quản trị chiều sâu nội bộ (Âm) để phát triển toàn diện.',
    });
  }

  // 7. Giáp Song Lộc (Song Lộc Giáp Cung)
  if ((hasLeft('Lộc Tồn') && hasRight('Hóa Lộc')) || (hasLeft('Hóa Lộc') && hasRight('Lộc Tồn'))) {
    results.push({
      type: 'hiep',
      label: 'Hiệp (Giáp Song Lộc)',
      stars: ['Lộc Tồn', 'Hóa Lộc'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Song Lộc Giáp Cung (雙祿夾命)',
      nature: 'cat',
      description: `Được cả Lộc Tồn và Hóa Lộc kẹp hai bên (${leftPalace.name} & ${rightPalace.name}), cung vị được bảo bọc bởi nguồn năng lượng tài lộc dồi dào, thuận lợi hanh thông trong việc tích lũy và thu hút của cải.`,
      actionableHint: 'Tận dụng các mối quan hệ vệ tinh để luân chuyển dòng vốn thông minh, tránh tiêu hoang phí.',
    });
  }

  // 8. Giáp Kình Đà (Kình Đà Giáp Sát)
  if ((hasLeft('Kình Dương') && hasRight('Đà La')) || (hasLeft('Đà La') && hasRight('Kình Dương'))) {
    results.push({
      type: 'hiepHung',
      label: 'Hiếp (Giáp Kình Đà)',
      stars: ['Kình Dương', 'Đà La'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Kình Đà Giáp Cung (羊陀夾命)',
      nature: 'hung',
      description: `Bản cung rơi vào thế bị Kình Dương và Đà La kẹp hai bên sườn (${leftPalace.name} & ${rightPalace.name}). Tâm lý dễ chịu nhiều áp lực đè nén, sự việc thường bị cản trở hoặc phải bước đi thận trọng như giữa hai lưỡi kiếm.`,
      actionableHint:
        'Giữ tâm lý kiên nhẫn, đi từng bước chắc chắn, không đốt cháy giai đoạn và hạn chế đối đầu trực diện.',
    });
  }

  // 9. Giáp Không Kiếp (Không Kiếp Giáp Cung)
  if ((hasLeft('Địa Không') && hasRight('Địa Kiếp')) || (hasLeft('Địa Kiếp') && hasRight('Địa Không'))) {
    results.push({
      type: 'hiepHung',
      label: 'Hiếp (Giáp Không Kiếp)',
      stars: ['Địa Không', 'Địa Kiếp'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Không Kiếp Giáp Cung (空劫夾命)',
      nature: 'hung',
      description: `Hai bên giáp cung ngộ Không Kiếp (${leftPalace.name} & ${rightPalace.name}), cảnh báo sự biến động bất ngờ từ môi trường lân cận, nguồn lực dễ bị phân tán hoặc có rủi ro bất khả kháng.`,
      actionableHint:
        'Luôn duy trì quỹ dự phòng an toàn, quản trị rủi ro nghiêm ngặt và không đầu tư mạo hiểm theo cảm tính.',
    });
  }

  // 10. Giáp Hỏa Linh (Hỏa Linh Giáp Cung)
  if ((hasLeft('Hỏa Tinh') && hasRight('Linh Tinh')) || (hasLeft('Linh Tinh') && hasRight('Hỏa Tinh'))) {
    results.push({
      type: 'hiepHung',
      label: 'Hiếp (Giáp Hỏa Linh)',
      stars: ['Hỏa Tinh', 'Linh Tinh'],
      sourcePalaces: [leftPalace.name, rightPalace.name],
      hostStars: hostChinhTinh,
      classicalPattern: 'Hỏa Linh Giáp Cung (火鈴夾命)',
      nature: 'hung',
      description: `Bị cặp Hỏa Tinh - Linh Tinh kẹp hai bên (${leftPalace.name} & ${rightPalace.name}), tạo áp lực nôn nóng, căng thẳng tinh thần hoặc dễ gặp biến cố xung đột bất thình lình.`,
      actionableHint:
        'Học cách kiềm chế cảm xúc, bình tĩnh quan sát trước khi phản ứng và chăm sóc giấc ngủ, sức khỏe thần kinh.',
    });
  }

  return results;
}

/**
 * Evaluates detailed Đối Cung (Triều / Xung) interactions between Host Stars and Guest Stars
 */
export function evaluateOppositionInteractions(palace: TuViPalace, allPalaces: TuViPalace[]): PositionalSemantic[] {
  const results: PositionalSemantic[] = [];
  const doiCungIdx = detectDoiCung(palace.id);
  const doiCungPalace = allPalaces[doiCungIdx];
  if (!doiCungPalace) return results;

  const hostChinhTinh = palace.chinhTinh.map((s) => s.name);
  const guestChinhTinh = doiCungPalace.chinhTinh;
  const guestSatTinhNames = doiCungPalace.satTinh.map((s) => s.name);
  const guestPhuTinhNames = doiCungPalace.phuTinh.map((s) => s.name);

  // 1. Cự Môn tại bản cung ngộ Thái Dương miếu/vượng xung chiếu (Hóa Ám Vi Minh)
  if (hostChinhTinh.includes('Cự Môn')) {
    const sunStar = guestChinhTinh.find((s) => s.name === 'Thái Dương');
    if (sunStar && ['Miếu', 'Vượng', 'Đắc'].includes(sunStar.brightness)) {
      results.push({
        type: 'trieu',
        label: 'Triều (Quang Huy Soi Chiếu)',
        stars: ['Thái Dương'],
        sourcePalaces: [doiCungPalace.name],
        hostStars: ['Cự Môn'],
        classicalPattern: 'Hóa Ám Vi Minh (化暗為明)',
        nature: 'cat',
        description: `Cự Môn (Ám tinh) tại bản cung được Thái Dương (${sunStar.brightness}) từ cung đối diện (${doiCungPalace.name}) quang minh rực rỡ chiếu thẳng vào, tạo thế "Hóa Ám Vi Minh". Hóa giải hoàn toàn nét nghi kỵ, chuyển hóa năng lực quan sát sâu sắc thành tài hùng biện, tư duy phản biện sắc bén và uy tín đối ngoại rực rỡ.`,
        actionableHint:
          'Tự tin phát biểu, tham gia thuyết trình hoặc dẫn dắt các hoạt động truyền thông, giao tế đối ngoại.',
      });
    } else if (sunStar && sunStar.brightness === 'Hãm') {
      results.push({
        type: 'xung',
        label: 'Xung (Ám Đới Trùng Trùng)',
        stars: ['Thái Dương (Hãm)'],
        sourcePalaces: [doiCungPalace.name],
        hostStars: ['Cự Môn'],
        classicalPattern: 'Nhật Ám Tương Tranh',
        nature: 'hung',
        description: `Cự Môn tại bản cung đối diện với Thái Dương hãm địa từ ${doiCungPalace.name}, nguồn sáng bị che mờ làm gia tăng tính đa nghi, dễ gặp hiểu lầm trong giao tiếp hoặc vướng thị phi khẩu thiệt từ bên ngoài.`,
        actionableHint:
          'Uốn lưỡi bảy lần trước khi nói, tránh tranh cãi không cần thiết và giữ minh bạch trong mọi tài liệu giấy tờ.',
      });
    }
  }

  // 2. Tham Lang tại bản cung ngộ Hỏa Tinh / Linh Tinh từ đối cung (Hỏa Tham / Linh Tham Triều Chiếu)
  if (hostChinhTinh.includes('Tham Lang')) {
    const hasHoaLinh = guestSatTinhNames.some((n) => ['Hỏa Tinh', 'Linh Tinh'].includes(n));
    if (hasHoaLinh) {
      const star = guestSatTinhNames.filter((n) => ['Hỏa Tinh', 'Linh Tinh'].includes(n)).join(', ');
      results.push({
        type: 'trieu',
        label: 'Triều (Kích Phát Bộc Phát)',
        stars: [star],
        sourcePalaces: [doiCungPalace.name],
        hostStars: ['Tham Lang'],
        classicalPattern: 'Hỏa Tham / Linh Tham Triều Cách (火鈴貪格)',
        nature: 'kich-phat',
        description: `Tham Lang tại bản cung đón nhận luồng kích phát mạnh mẽ từ ${star} ở đối cung (${doiCungPalace.name}). Báo hiệu những thời cơ bứt phá đột biến về tài lộc và sự nghiệp khi dám nghĩ dám làm và nhanh nhạy với thời cuộc.`,
        actionableHint:
          'Nhanh chóng nắm bắt cơ hội khi thời cơ xuất hiện, nhưng cần có kế hoạch quản trị rủi ro để giữ vững thành quả.',
      });
    }
  }

  // 3. Cung Vô Chính Diệu mượn lực từ Đối Cung
  if (hostChinhTinh.length === 0 && guestChinhTinh.length > 0) {
    const brightStars = guestChinhTinh.filter((s) => ['Miếu', 'Vượng', 'Đắc'].includes(s.brightness));
    if (brightStars.length > 0) {
      results.push({
        type: 'trieu',
        label: 'Triều (Chính Tinh Đối Chiếu)',
        stars: brightStars.map((s) => `${s.name} (${s.brightness})`),
        sourcePalaces: [doiCungPalace.name],
        hostStars: ['Vô Chính Diệu'],
        classicalPattern: 'Tá Cung Chiếu Mệnh (借宮照命)',
        nature: 'cat',
        description: `Do bản cung Vô Chính Diệu, cung vị mượn trọn vẹn 70–80% năng lượng đắc cách của ${brightStars.map((s) => `${s.name} (${s.brightness})`).join(', ')} từ đối cung (${doiCungPalace.name}). Giúp đương số có tư duy linh hoạt, thích nghi nhanh và tận dụng tối đa cơ hội từ môi trường ngoài.`,
        actionableHint:
          'Dựa vào ngoại lực và quý nhân để mở đường, rèn luyện tính độc lập để không bị phụ thuộc hoàn toàn vào ngoại cảnh.',
      });
    }
  }

  // 4. Lộc Tồn / Hóa Lộc tại bản cung bị Sát tinh đối cung trực xung (Lộc phùng Xung Phá)
  const hasHostLoc = palace.tuHoa.some((th) => th.type === 'Lộc') || palace.phuTinh.some((s) => s.name === 'Lộc Tồn');
  const hasGuestSat = guestSatTinhNames.some((n) => ['Địa Không', 'Địa Kiếp', 'Kình Dương', 'Đà La'].includes(n));
  if (hasHostLoc && hasGuestSat) {
    const satStr = guestSatTinhNames
      .filter((n) => ['Địa Không', 'Địa Kiếp', 'Kình Dương', 'Đà La'].includes(n))
      .join(', ');
    results.push({
      type: 'xung',
      label: 'Xung (Lộc Phùng Xung Phá)',
      stars: [satStr],
      sourcePalaces: [doiCungPalace.name],
      hostStars: ['Lộc Tồn / Hóa Lộc'],
      classicalPattern: 'Lộc Phùng Xung Phá (祿逢沖破)',
      nature: 'hung',
      description: `Nguồn tài lộc tại bản cung bị ${satStr} từ đối cung (${doiCungPalace.name}) trực xung dòm ngó. Dù kiếm tiền thuận lợi nhưng dễ phát sinh các khoản chi ngoài dự tính hoặc biến động thị trường bất ngờ làm hao tán.`,
      actionableHint:
        'Thực hiện phương châm "ăn chắc mặc bền", tái đầu tư vào tài sản an toàn, không tham gia đầu cơ có tính phiêu lưu.',
    });
  }

  // 5. Thiên Phủ tại bản cung ngộ Không Kiếp đối cung xung (Không Khố)
  if (hostChinhTinh.includes('Thiên Phủ') && guestSatTinhNames.some((n) => ['Địa Không', 'Địa Kiếp'].includes(n))) {
    results.push({
      type: 'xung',
      label: 'Xung (Khố Tinh Phùng Không)',
      stars: ['Địa Không / Địa Kiếp'],
      sourcePalaces: [doiCungPalace.name],
      hostStars: ['Thiên Phủ'],
      classicalPattern: 'Lộ Khố / Không Khố (露庫空庫)',
      nature: 'hung',
      description: `Tài khố Thiên Phủ tại bản cung bị Địa Không/Địa Kiếp từ đối cung (${doiCungPalace.name}) trực xung, cảnh báo nguy cơ rò rỉ tài chính, bị đối tác vay mượn khó đòi hoặc đầu tư thất thoát nếu thiếu giám sát chặt chẽ.`,
      actionableHint: 'Thiết lập kỷ luật kiểm toán nghiêm ngặt, giữ gìn tài sản cẩn mật và tránh phô trương tài chính.',
    });
  }

  // 6. Cát Tinh / Tứ Hóa Triều Chiếu tổng quát
  const majorGoodTrieu = [
    ...guestChinhTinh.filter((s) => ['Miếu', 'Vượng', 'Đắc'].includes(s.brightness)).map((s) => s.name),
    ...guestPhuTinhNames.filter((n) =>
      [
        'Tả Phụ',
        'Hữu Bật',
        'Thiên Khôi',
        'Thiên Việt',
        'Văn Xương',
        'Văn Khúc',
        'Hóa Khoa',
        'Hóa Quyền',
        'Hóa Lộc',
      ].includes(n),
    ),
  ];
  if (majorGoodTrieu.length > 0 && results.every((r) => r.type !== 'trieu')) {
    results.push({
      type: 'trieu',
      label: 'Triều (Cát Tinh Hội Chiếu)',
      stars: Array.from(new Set(majorGoodTrieu)),
      sourcePalaces: [doiCungPalace.name],
      hostStars: hostChinhTinh,
      nature: 'cat',
      description: `Đối cung (${doiCungPalace.name}) hội tụ các cát tinh (${Array.from(new Set(majorGoodTrieu)).join(', ')}) rọi chiếu về, tạo nguồn trợ lực quý giá từ môi trường đối ngoại và cơ hội giao lưu bên ngoài.`,
    });
  }

  // 7. Sát Tinh Trực Xung tổng quát
  const majorSatXung = guestSatTinhNames.filter((n) =>
    ['Kình Dương', 'Đà La', 'Hỏa Tinh', 'Linh Tinh', 'Địa Không', 'Địa Kiếp'].includes(n),
  );
  if (majorSatXung.length > 0 && results.every((r) => r.type !== 'xung')) {
    results.push({
      type: 'xung',
      label: 'Xung (Sát Tinh Trực Xung)',
      stars: majorSatXung,
      sourcePalaces: [doiCungPalace.name],
      hostStars: hostChinhTinh,
      nature: 'hung',
      description: `Từ đối cung (${doiCungPalace.name}) có các sát tinh (${majorSatXung.join(', ')}) trực xung, đòi hỏi đương số luôn giữ sự bình tĩnh, cẩn trọng trước các biến động ngoại cảnh và áp lực cạnh tranh.`,
      actionableHint: 'Duy trì thế phòng thủ vững chắc, kiểm soát rủi ro và không hành động nóng vội.',
    });
  }

  return results;
}

/**
 * Evaluates detailed Tam Phương (Củng) Trine interactions
 */
export function evaluateTrineInteractions(palace: TuViPalace, allPalaces: TuViPalace[]): PositionalSemantic[] {
  const results: PositionalSemantic[] = [];
  const tamHopIndices = detectTamHopPalaces(palace.id);
  const tamHopPalaces = tamHopIndices.map((i) => allPalaces[i]).filter((p): p is TuViPalace => Boolean(p));
  if (tamHopPalaces.length === 0) return results;

  const hostChinhTinh = palace.chinhTinh.map((s) => s.name);
  const thPalaceNames = tamHopPalaces.map((p) => p.name);

  const thAllStars = tamHopPalaces.flatMap((p) => [
    ...p.chinhTinh.map((s) => ({ star: s.name, brightness: s.brightness, palace: p.name })),
    ...p.phuTinh.map((s) => ({ star: s.name, brightness: s.brightness, palace: p.name })),
    ...p.satTinh.map((s) => ({ star: s.name, brightness: s.brightness, palace: p.name })),
  ]);

  const hasInTH = (starName: string) => thAllStars.some((s) => s.star === starName);

  // 1. Quân Thần Khánh Hội (君臣慶會) — Tử Vi / Thiên Phủ ngộ Tả Hữu tam hợp
  const isDeTinh = hostChinhTinh.some((n) => ['Tử Vi', 'Thiên Phủ'].includes(n));
  if (isDeTinh && (hasInTH('Tả Phụ') || hasInTH('Hữu Bật'))) {
    const troTinh = ['Tả Phụ', 'Hữu Bật'].filter(hasInTH).join(' và ');
    results.push({
      type: 'cung',
      label: 'Củng (Quân Thần Khánh Hội)',
      stars: [troTinh],
      sourcePalaces: thPalaceNames,
      hostStars: hostChinhTinh.filter((n) => ['Tử Vi', 'Thiên Phủ'].includes(n)),
      classicalPattern: 'Quân Thần Khánh Hội (君臣慶會)',
      nature: 'cat',
      description: `Đế tinh tại bản cung đón nhận thế củng chiếu "Quân Thần Khánh Hội" từ ${troTinh} trong thế chân vạc tam hợp (${thPalaceNames.join(', ')}). Tạo nên phong thái lãnh đạo khoan hòa, có mưu lược sâu rộng và được đông đảo cấp dưới, bạn bè đồng lòng phò tá.`,
      actionableHint:
        'Biết lắng nghe ý kiến phản biện từ cấp dưới, trao quyền hợp lý để quy tụ nhân tài cùng phát triển.',
    });
  }

  // 2. Khoa Giáp Trùng Phùng (Khoa giáp tinh củng chiếu Cơ Nguyệt Đồng Lương / Tử Phủ)
  const isTriTueHost = hostChinhTinh.some((n) =>
    ['Thiên Cơ', 'Thái Âm', 'Thiên Đồng', 'Thiên Lương', 'Tử Vi', 'Vũ Khúc'].includes(n),
  );
  const hasKhoaGiap = ['Văn Xương', 'Văn Khúc', 'Thiên Khôi', 'Thiên Việt', 'Hóa Khoa'].filter(hasInTH);
  if (isTriTueHost && hasKhoaGiap.length >= 2) {
    results.push({
      type: 'cung',
      label: 'Củng (Khoa Bảng Tương Trợ)',
      stars: hasKhoaGiap,
      sourcePalaces: thPalaceNames,
      hostStars: hostChinhTinh,
      classicalPattern: 'Khoa Giáp Trùng Phùng (科甲重逢)',
      nature: 'cat',
      description: `Tam phương (${thPalaceNames.join(', ')}) hội tụ các văn tinh sáng giá (${hasKhoaGiap.join(', ')}), tương trợ đắc lực cho tư duy chiến lược và năng lực học vấn của bản cung, giúp đường công danh thi cử và học vị rộng mở.`,
      actionableHint: 'Đầu tư chuyên sâu vào bằng cấp, chứng chỉ chuyên môn và công tác nghiên cứu hoạch định.',
    });
  }

  // 3. Lộc Mã Giao Trì (Lộc và Mã củng hợp)
  const hasLoc =
    hasInTH('Lộc Tồn') ||
    hasInTH('Hóa Lộc') ||
    palace.phuTinh.some((s) => s.name === 'Lộc Tồn') ||
    palace.tuHoa.some((th) => th.type === 'Lộc');
  const hasMa = hasInTH('Thiên Mã') || palace.phuTinh.some((s) => s.name === 'Thiên Mã');
  if (hasLoc && hasMa) {
    results.push({
      type: 'cung',
      label: 'Củng (Lộc Mã Giao Trì)',
      stars: ['Thiên Mã', 'Lộc Tồn / Hóa Lộc'],
      sourcePalaces: thPalaceNames,
      hostStars: hostChinhTinh,
      classicalPattern: 'Lộc Mã Giao Trì (祿馬交馳)',
      nature: 'cat',
      description: `Thế củng chiếu tạo nên cách cục "Lộc Mã Giao Trì" giữa tài tinh và dịch mã trong mạng lưới tam phương. Chủ về sự năng động, đi xa lập nghiệp dễ phát tài, càng bôn ba giao thương càng thu hoạch dồi dào.`,
      actionableHint: 'Tích cực đi lại, mở rộng mạng lưới kinh doanh liên vùng hoặc phát triển thương mại đối ngoại.',
    });
  }

  // 4. Hỏa Tham / Linh Tham Củng Chiếu
  if (hostChinhTinh.includes('Tham Lang') && (hasInTH('Hỏa Tinh') || hasInTH('Linh Tinh'))) {
    const fireStar = ['Hỏa Tinh', 'Linh Tinh'].filter(hasInTH).join(', ');
    results.push({
      type: 'cung',
      label: 'Củng (Hỏa Tham / Linh Tham Hợp Cách)',
      stars: [fireStar],
      sourcePalaces: thPalaceNames,
      hostStars: ['Tham Lang'],
      classicalPattern: 'Hỏa Tham / Linh Tham Hợp Cung',
      nature: 'kich-phat',
      description: `Tham Lang bản cung hội cùng ${fireStar} từ tam phương (${thPalaceNames.join(', ')}), tăng cường tính quyết đoán, khả năng đột phá và đem lại những vận hội may mắn về tài lộc bất ngờ.`,
      actionableHint:
        'Quyết đoán nắm bắt thời cơ khi thiên thời địa lợi hội tụ, nhưng luôn trích quỹ tích lũy an toàn.',
    });
  }

  // 5. Tam Phương Cát Tinh Củng Chiếu tổng quát
  const goodStars = thAllStars
    .filter(
      (s) =>
        [
          'Tả Phụ',
          'Hữu Bật',
          'Thiên Khôi',
          'Thiên Việt',
          'Văn Xương',
          'Văn Khúc',
          'Lộc Tồn',
          'Thiên Mã',
          'Hóa Lộc',
          'Hóa Quyền',
          'Hóa Khoa',
        ].includes(s.star) || ['Miếu', 'Vượng', 'Đắc'].includes(s.brightness),
    )
    .map((s) => s.star);
  const uniqueGood = Array.from(new Set(goodStars));
  if (uniqueGood.length > 0 && results.length === 0) {
    results.push({
      type: 'cung',
      label: 'Củng (Tam Phương Nâng Đỡ)',
      stars: uniqueGood.slice(0, 5),
      sourcePalaces: thPalaceNames,
      hostStars: hostChinhTinh,
      nature: 'cat',
      description: `Tam phương (${thPalaceNames.join(', ')}) có các cát tinh (${uniqueGood.slice(0, 5).join(', ')}) hợp lực nâng đỡ, củng cố thế trận vững chãi cho cung ${palace.name}.`,
    });
  }

  return results;
}

/**
 * Evaluates detailed Tọa & Cứ (Resident / Host-Internal) interactions
 */
export function evaluateResidentInteractions(palace: TuViPalace): PositionalSemantic[] {
  const results: PositionalSemantic[] = [];
  const hostChinhTinh = palace.chinhTinh;
  const hostSatTinh = palace.satTinh;
  const goodPhuTinh = palace.phuTinh.filter(
    (s) =>
      [
        'Tả Phụ',
        'Hữu Bật',
        'Văn Xương',
        'Văn Khúc',
        'Thiên Khôi',
        'Thiên Việt',
        'Lộc Tồn',
        'Thiên Mã',
        'Đào Hoa',
        'Hồng Loan',
        'Hóa Khoa',
        'Hóa Lộc',
        'Hóa Quyền',
      ].includes(s.name) ||
      s.grade === 'giap' ||
      s.grade === 'at',
  );

  // 1. Tọa (Chính tinh & Cát tinh tọa thủ và sự phối hợp nội cung)
  const toaStarList = [...hostChinhTinh.map((s) => `${s.name} (${s.brightness})`), ...goodPhuTinh.map((s) => s.name)];

  if (toaStarList.length > 0) {
    const isBrightAll =
      hostChinhTinh.length > 0 && hostChinhTinh.every((s) => ['Miếu', 'Vượng', 'Đắc'].includes(s.brightness));
    const isDimAll = hostChinhTinh.length > 0 && hostChinhTinh.every((s) => s.brightness === 'Hãm');

    let nature: 'cat' | 'hung' | 'trung-hoa' | 'kich-phat' = 'trung-hoa';
    let detailNote = '';

    if (hostChinhTinh.length === 2) {
      const pair = hostChinhTinh
        .map((s) => s.name)
        .sort()
        .join(' - ');
      detailNote = `Thế song tinh đồng cung **${pair}** phối hợp năng lượng: `;
      if (['Tử Vi', 'Thiên Phủ'].every((n) => hostChinhTinh.some((s) => s.name === n))) {
        detailNote +=
          'Tử Phủ đồng cung tạo nên phong thái đế vương kết hợp tài khố trù phú, tính tình đĩnh đạc, mưu sự chu toàn.';
        nature = 'cat';
      } else if (['Tử Vi', 'Thất Sát'].every((n) => hostChinhTinh.some((s) => s.name === n))) {
        detailNote +=
          'Tử Sát đồng cung ("Hóa sát vi quyền"): biến hung tính thành uy quyền dũng mãnh, tinh thần tiên phong mở lối.';
        nature = 'kich-phat';
      } else if (['Vũ Khúc', 'Tham Lang'].every((n) => hostChinhTinh.some((s) => s.name === n))) {
        detailNote +=
          'Vũ Tham đồng cung ("Tiền bần hậu phú"): tuổi trẻ cần tôi luyện bôn ba, càng về trung hậu vận tài lộc càng rực rỡ.';
        nature = 'trung-hoa';
      } else if (['Thái Dương', 'Thái Âm'].every((n) => hostChinhTinh.some((s) => s.name === n))) {
        detailNote +=
          'Nhật Nguyệt đồng cung: nội tâm phong phú, đa tài đa nghệ, cần giữ tính kiên định để tránh tâm lý dao động.';
        nature = 'trung-hoa';
      } else {
        detailNote += isBrightAll
          ? 'Cả hai chính tinh đều miếu vượng, củng cố cốt cách bản cung vững vàng.'
          : 'Cần phát huy ưu thế của chính tinh miếu vượng và tiết chế nhược điểm của chính tinh hãm.';
        nature = isBrightAll ? 'cat' : 'trung-hoa';
      }
      if (goodPhuTinh.length > 0) {
        detailNote += ` Đồng tọa cùng các cát tinh (${goodPhuTinh.map((s) => s.name).join(', ')}) gia tăng thêm trợ lực quý báu.`;
      }
    } else if (hostChinhTinh.length === 1) {
      detailNote = isBrightAll
        ? `Chính tinh tọa thủ miếu vượng (${hostChinhTinh[0].name} ${hostChinhTinh[0].brightness}), định hình cốt cách tự chủ, tài năng và phẩm chất lãnh đạo vững vàng.`
        : isDimAll
          ? `Chính tinh tọa thủ hãm địa (${hostChinhTinh[0].name} ${hostChinhTinh[0].brightness}), cần sự tôi luyện ý chí, học hỏi từ nghịch cảnh để vươn lên.`
          : `Chính tinh tọa thủ (${hostChinhTinh[0].name} ${hostChinhTinh[0].brightness}), mang lại bản sắc đặc thù cho cung vị.`;
      if (goodPhuTinh.length > 0) {
        detailNote += ` Được phò tá bởi các cát tinh (${goodPhuTinh.map((s) => s.name).join(', ')}).`;
      }
      nature = isBrightAll ? 'cat' : isDimAll ? 'hung' : 'trung-hoa';
    } else {
      // Vô Chính Diệu nhưng có Cát tinh tọa thủ
      detailNote = `Bản cung Vô Chính Diệu được các cát tinh tọa thủ (${goodPhuTinh.map((s) => s.name).join(', ')}) quy tụ giữ vai trò nòng cốt định hình trường khí bản cung.`;
      nature = 'cat';
    }

    results.push({
      type: 'toa',
      label: 'Tọa (Chính Tinh & Cát Tinh Tọa Thủ)',
      stars: toaStarList,
      sourcePalaces: [palace.name],
      hostStars: hostChinhTinh.map((s) => s.name),
      nature,
      description: detailNote,
    });
  }

  // 2. Cứ (Sát tinh chiếm cứ bản cung và xung đột nội cung)
  const satGradeA = hostSatTinh.filter(
    (s) =>
      ['Kình Dương', 'Đà La', 'Hỏa Tinh', 'Linh Tinh', 'Địa Không', 'Địa Kiếp', 'Thiên Hình', 'Hóa Kỵ'].includes(
        s.name,
      ) || s.grade === 'giap',
  );
  if (satGradeA.length > 0) {
    const satList = satGradeA.map((s) => `${s.name}${s.brightness ? ` (${s.brightness})` : ''}`).join(', ');
    const hasBrightSat = satGradeA.some((s) => s.brightness === 'Đắc' || s.brightness === 'Miếu');

    let satDesc = '';
    if (hasBrightSat) {
      satDesc = `Bản cung có sát tinh đắc địa (${satList}) chiếm cứ: Hung tinh đắc địa biến hóa thành động lực bứt phá mãnh liệt, tôi luyện bản lĩnh gan dạ trước sóng gió.`;
    } else {
      satDesc = `Bản cung bị các sát tinh (${satList}) chiếm cứ: Đòi hỏi sự cẩn trọng cao độ trong hành động, kiểm soát tính khí nóng vội và phòng ngừa rủi ro hao tổn.`;
    }

    results.push({
      type: 'cu',
      label: 'Cứ (Sát Tinh Chiếm Cứ)',
      stars: satGradeA.map((s) => s.name),
      sourcePalaces: [palace.name],
      hostStars: hostChinhTinh.map((s) => s.name),
      nature: hasBrightSat ? 'kich-phat' : 'hung',
      description: satDesc,
      actionableHint:
        'Dùng kỷ luật và sự điềm tĩnh để chế ngự sát khí, chuyển hóa áp lực thành động lực hoàn thiện bản thân.',
    });
  }

  return results;
}

/**
 * Evaluates detailed Nhị Hợp (Lục Hợp) Branch Interaction with Elemental Dynamics
 */
export function evaluateNhiHopBranchInteraction(palace: TuViPalace, allPalaces: TuViPalace[]): string | undefined {
  const nhiHopIdx = palace.nhiHopPalaceIndex ?? detectNhiHopPalace(palace.id);
  const nhiHopPalace = allPalaces[nhiHopIdx];
  if (!nhiHopPalace) return undefined;

  const hostElem = BRANCH_ELEMENT[palace.chi] ?? 'Thổ';
  const targetElem = BRANCH_ELEMENT[nhiHopPalace.chi] ?? 'Thổ';
  const relation = getElementRelation(hostElem, targetElem);

  const nhiHopMajorStars = nhiHopPalace.chinhTinh.map((s) => `${s.name} (${s.brightness})`);
  const nhiHopTuHoa = nhiHopPalace.tuHoa.map((th) => `Hóa ${th.type}`);
  const nhiHopSat = nhiHopPalace.satTinh.map((s) => s.name);

  let elemDesc = '';
  switch (relation) {
    case 'sinh_nhap':
      elemDesc = `Cung ${nhiHopPalace.name} (${nhiHopPalace.chi} — ${targetElem}) tương sinh cho cung ${palace.name} (${palace.chi} — ${hostElem}) theo thế Sinh Nhập: Mang lại nguồn sinh khí và trợ lực ngầm quý giá.`;
      break;
    case 'sinh_xuat':
      elemDesc = `Cung ${palace.name} (${palace.chi} — ${hostElem}) tương sinh cho cung ${nhiHopPalace.name} (${nhiHopPalace.chi} — ${targetElem}) theo thế Sinh Xuất: Đương số thường phải dành nhiều tâm lực, cống hiến ngầm cho phương diện này.`;
      break;
    case 'khac_nhap':
      elemDesc = `Cung ${nhiHopPalace.name} (${nhiHopPalace.chi} — ${targetElem}) tương khắc cung ${palace.name} (${palace.chi} — ${hostElem}) theo thế Khắc Nhập: Tiềm ẩn áp lực kiềm tỏa ngầm, cần sự khéo léo dung hòa.`;
      break;
    case 'khac_xuat':
      elemDesc = `Cung ${palace.name} (${palace.chi} — ${hostElem}) khắc chế cung ${nhiHopPalace.name} (${nhiHopPalace.chi} — ${targetElem}) theo thế Khắc Xuất: Đương số có thế chủ động kiểm soát và dẫn dắt mối quan hệ ngầm này.`;
      break;
    case 'ty_hoa':
      elemDesc = `Cung ${palace.name} và ${nhiHopPalace.name} đồng khí ngũ hành (${hostElem}): Tương hòa, dễ đồng cảm và gắn kết tự nhiên.`;
      break;
  }

  const starSummary = nhiHopMajorStars.length > 0 ? ` (quy tụ ${nhiHopMajorStars.join(', ')})` : '';
  const tuHoaSummary = nhiHopTuHoa.length > 0 ? ` kết hợp ${nhiHopTuHoa.join(', ')}` : '';
  const satNote = nhiHopSat.length > 0 ? ` (Lưu ý ảnh hưởng ngầm từ ${nhiHopSat.slice(0, 3).join(', ')})` : '';

  return `Nhị Hợp với cung ${nhiHopPalace.name} (${nhiHopPalace.chi}): ${elemDesc} Nội lực từ ${nhiHopPalace.name}${starSummary}${tuHoaSummary}${satNote} tạo nên mạch liên kết bền chặt phía sau hậu trường.`;
}
